#!/usr/bin/perl

# ================================================
# booting script for google code jam 2009
# ================================================

use strict;
use warnings;

# ===============
# parse arguments
# ===============

# how to get argv[0]
my $probName = shift;
my $path = shift or die("Useage: $0 <problem name> <path>\n");

# ===============
# prepare directories, etc.
# ===============
my $probPath = $path . "/" . $probName;
unless (-d $probPath) {
    system "mkdir $probPath";
}
system "touch " . $probPath . "/testinput";

# ===============
# print code
# ===============

my $cppName = $probPath . "/" . $probName . ".cpp";

open my $fh, ">", "$cppName";

print $fh <<'END';
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <algorithm>
#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <utility>
#include <set>
#include <cctype>
#include <queue>
#include <stack>
#include <fstream>

using namespace std;

vector <int> split(const string _s, const string del = " ");
vector <string> splits(const string _s, const string del = " ");
int toInt(string s) {int r = 0; istringstream ss(s); ss >> r; return r;}
string toStr(int n) {ostringstream ss; ss << n; return ss.str();}

string run(string input)
{
  string ret;



  return ret;
}

int main(int argc, char ** argv)
{
  if (argc != 2)
  {
    cout << "Usage " << argv[0] << " <input file name>\n";
    return 0;
  }

  ifstream file (argv[1]);
  string line;
  vector <int> args;

  getline(file, line);
  args = split(line);

  for (int lineNum = 0; lineNum<args[0]; lineNum++)
    {
      string result;

      getline(file, line);

      result = run(line);

      cout << "Case #" << lineNum+1 << ": " << result << endl;
    }

  return 0;
}

vector <int> split(const string _s, const string del)
{
  vector <int> ret;
  string s = _s;

  while (!s.empty())
    {
      size_t pos = s.find(del);
      string sub = "";
      sub = s.substr(0, pos);
      ret.push_back(toInt(sub));
      if (pos != string::npos)
	pos += del.size();
      s.erase(0, pos);
    }

  return ret;
}

vector <string> splits(const string _s, const string del)
{
  vector <string> ret;
  string s = _s;

  while (!s.empty())
    {
      size_t pos = s.find(del);
      string sub = "";
      sub = s.substr(0, pos);
      ret.push_back(sub);
      if (pos != string::npos)
	pos += del.size();
      s.erase(0, pos);
    }

  return ret;
}
END

close $fh;

